artifacts_root: artifacts

data_ingestion:
     root_dir: artifacts/data_ingestion
     source_url: https://github.com/Tejesh0209/NewprojectDS/raw/refs/heads/main/finance_data.csv.zip
     local_data_file: artifacts/data_ingestion/data.zip
     unzip_dir: artifacts/data_ingestion